# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Not a postal code', regex='^\\d{4}$')])),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='A phone number is 9 digits', regex='^\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Narocilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanitity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('supply', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0)),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the start of the promotion')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the end of the promotion')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0)),
                ('id_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='narocilo',
            name='id_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='narocilo',
            name='id_Receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Receipt'),
        ),
        migrations.AddField(
            model_name='address',
            name='id_Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
        ),
    ]
