# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170113_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
    ]
