# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_address_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address',
        ),
    ]
