# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=40),
        ),
    ]
