# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170115_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
