# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170115_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
